// Imports required modules
const notes = require("express").Router();
const {
  readFromFile,
  readAndAppend,
  deleteById,
} = require("../helpers/fsUtil");
const { v4: uuidv4 } = require("uuid");

// Variable for JSON file path
const file = "./db/db.json";

// Get route for retrieving the notes by reading the JSON file
notes.get("/", (req, res) => {
  // Calls the readFromFile function and passes the file path then returns parsed JSON data
  readFromFile(file).then((data) => res.json(JSON.parse(data)));
});

// Post route for adding the notes
notes.post("/", (req, res) => {
  // Retrieves the title and text of the note from the request body
  const { title, text } = req.body;

  // If the req.body is truthy
  if (req.body) {
    // Create an object with the title, text, and an ID generated by uuid
    const newNote = {
      title,
      text,
      id: uuidv4(),
    };
    // Call the readAndAppend function with the file path and the note object we want to add
    readAndAppend(file, newNote);

    // Sends a JSON response back
    res.json(`Successfully added a note with ID: ${newNote.id}`);
  }
});

// Delete route for removing the notes
notes.delete("/:id", (req, res) => {
  // Retrieves the id of the note the request was made with
  const noteId = req.params.id;

  // Calls the deleteById function and passes it the file path and note id
  deleteById(file, noteId);

  // Sends a JSON response back
  res.json(`Deleted the note with ID: ${noteId}`);
});

// Exports our modularized route
module.exports = notes;
